### ISSUE TITLE
Docker IP issue

### ISSUE THREAD

**Issue by C8opmBM** [whi-tw/docker-xteve#1]
Hello and thanks for this image, its the only one with flexible puid guid that I found. And I've tried many.

My issue is with the docker ip which breaks my plex server whenever it updates the xmltv and xepg.

The only workaround I found is to run a script when I update the image. Unfortunately this involves curl. It would be something like this, after creation:

`docker exec -it xteve sh -c "curl -X POST -d '{"cmd":"update.xmltv"}' http://myxTeveIP:xTevePORT/api/ && curl -X POST -d '{"cmd":"update.xepg"}' http://myxTeveIP:xTevePORT/api/"`

Would you be so kind as to include curl? I tried to fork it and add it myself, but my knowledge is limited and failed to build it on dockerhub.

Or, may I ask you, how do you get to solve the docker ip issue?
I use a reverseproxy with linuxserver:letsencrypt.
My docker container with xteve:

```
  xteve:
    depends_on:
      - ReverseProxy
    image: tnwhitwell/xteve
    restart: unless-stopped
    environment:
      - TZ=Europe/Bucharest
    volumes:
      - /sharedfolders/mediatools/xteve:/config
      - /sharedfolders/mediatools/xteve_tmp:/tmp/xteve
    ports:
      - 34400:34400     
    user: "1001:100"
    networks:
      - media    
    container_name: xteve
```

After reboot or recreation, my links become:
https://172.xxxx:443/images/8ff4ba1d290911d313ed0d4c9b66a9ba.png
whereas I need them 
https://mydomain:443/images/8ff4ba1d290911d313ed0d4c9b66a9ba.png

Thank you very much!
